#SETUP

require "fileutils"

#Link to Bootstrap via CDN
bootstrap_css = '<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">'
bootstrap_optional_theme = '<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">'
boostrap_js = '<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>'

#Link to Purecss
purecss = '<link rel="stylesheet" href="https://unpkg.com/purecss@1.0.0/build/pure-min.css" integrity="sha384-nn4HPE8lTHyVtfCBi5yW9d20FjT8BJwUXyWZT9InLYax14RDjBj46LmSztkmNP9w" crossorigin="anonymous">'

#Making folder structure

folder_name = "template-project" 

FileUtils::mkdir_p folder_name
FileUtils::mkdir_p folder_name + "/html"
FileUtils::mkdir_p folder_name + "/js"
FileUtils::mkdir_p folder_name + "/css"
FileUtils::mkdir_p folder_name + "/images"

#Making individual files

FileUtils::touch folder_name + "/html/index.html"
FileUtils::touch folder_name + "/css/style.css"

css_path = folder_name + "/css/style.css"

#Filling those files with html/css

#Writing HTML template

File.open("template-project/html/index.html", 'w') {
	|f| 
	f.puts("<!DOCTYPE html>")
	f.puts("<html>")
	f.puts("<head>")
	f.puts("")
	#Comment out these three bootstrap lines to get rid of bootstrap
	f.puts(bootstrap_css)
	f.puts("")
	f.puts(bootstrap_optional_theme)
	f.puts("")
	f.puts(boostrap_js)
	f.puts("")
	#Uncomment this Purecss line to use purecss instead of Bootstrap. You'll have to
	#comment out the bootstrap lines above.
#	f.puts(purecss)
	f.puts("")
	f.puts('<link rel="stylesheet" href="' + css_path + '">')
	f.puts("    <title>" + folder_name + "</title>")
	f.puts("</head>")
	f.puts("<body>")
	f.puts("")
	f.puts("</body>")
	f.puts("</html>")
	f.puts("<!-- Template lovingly generated by Launchpad -->")
}	

#Writing to CSS file