#SETUP

require "fileutils"

project_folder = "template-project"

sub_folders = ["", "/html", "/js", "/css", "/images"]

web_files = ["/html/index.html", "/css/style.css"]

def new_folder(foldername)
  FileUtils::mkdir_p foldername
end

def new_file(filepath)
  FileUtils::touch filepath
end

#Link to Bootstrap via CDN
bootstrap_css = '<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">'
bootstrap_optional_theme = '<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">'
boostrap_js = '<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>'

#Link to Purecss
purecss = '<link rel="stylesheet" href="https://unpkg.com/purecss@1.0.0/build/pure-min.css" integrity="sha384-nn4HPE8lTHyVtfCBi5yW9d20FjT8BJwUXyWZT9InLYax14RDjBj46LmSztkmNP9w" crossorigin="anonymous">'

#Making folder structure
sub_folders.each { |subfolder| new_folder(project_folder + subfolder) }

#Making individual html and css files
web_files.each { |webfile| new_file(project_folder + webfile)}

#Writing HTML template to index.html

File.open("html_template.txt").each do |line|
  File.open(project_folder+"/html/index.html", "a+") { |file| file.write(line) }
end


File.open(project_folder+"/html/index.html", "a+") {|file| file.write("<!-- Template lovingly generated by Launchpad -->")}
