#SETUP

require "fileutils"

#Link to Bootstrap via CDN
bootstrap_css = '<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">'
bootstrap_optional_theme = '<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">'
boostrap_js = '<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>'

#Link to Purecss
purecss = '<link rel="stylesheet" href="https://unpkg.com/purecss@1.0.0/build/pure-min.css" integrity="sha384-nn4HPE8lTHyVtfCBi5yW9d20FjT8BJwUXyWZT9InLYax14RDjBj46LmSztkmNP9w" crossorigin="anonymous">'

#Making folder structure

folder_name = "template-project"

FileUtils::mkdir_p folder_name
FileUtils::mkdir_p folder_name + "/html"
FileUtils::mkdir_p folder_name + "/js"
FileUtils::mkdir_p folder_name + "/css"
FileUtils::mkdir_p folder_name + "/images"

#Making individual files

FileUtils::touch folder_name + "/html/index.html"
FileUtils::touch folder_name + "/css/style.css"

css_path = folder_name + "/css/style.css"

#Filling those files with html/css

#Writing HTML template to index.html


File.open("html_template.txt").each do |line|
  File.open("index.html", "a+") { |file| file.write(line) }
end


File.open("index.html", "a+") {|file| file.write("<!-- Template lovingly generated by Launchpad -->")}
